#!/usr/bin/env -S npx tsx

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

function valueFor(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag);
  if (index === -1) return undefined;

  const value = args[index + 1];
  return value && !value.startsWith("--") ? value : undefined;
}

function usage(): void {
  console.error(
    'Usage: npx tsx skills/brain/scripts/configure-brain.ts --vault-name "vault-name" --vault-path "/absolute/path/to/vault"',
  );
}

function markdownInlineCode(value: string): string {
  return `\`${value.replaceAll("`", "\\`")}\``;
}

const args = process.argv.slice(2);
const vaultName = valueFor(args, "--vault-name");
const vaultPath = valueFor(args, "--vault-path");

if (!vaultName || !vaultPath) {
  usage();
  process.exit(1);
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const configPath = resolve(scriptDir, "../references/brain-config.md");

mkdirSync(dirname(configPath), { recursive: true });
writeFileSync(
  configPath,
  [
    "# Brain Config",
    "",
    `Vault name: ${markdownInlineCode(vaultName)}`,
    `Vault path: ${markdownInlineCode(vaultPath)}`,
    "",
    "Generated by `scripts/configure-brain.ts`.",
    "",
  ].join("\n"),
  "utf8",
);

console.log(`Wrote ${configPath}`);
