#!/usr/bin/env -S npx tsx

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

function valueFor(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag);
  if (index === -1) return undefined;

  const value = args[index + 1];
  return value && !value.startsWith("--") ? value : undefined;
}

function usage(): void {
  console.error(
    'Usage: npx tsx skills/attribution/scripts/configure-attribution.ts --name "Agent Name" --emoji "symbol"',
  );
}

function markdownInlineCode(value: string): string {
  return `\`${value.replaceAll("`", "\\`")}\``;
}

const args = process.argv.slice(2);
const name = valueFor(args, "--name");
const emoji = valueFor(args, "--emoji");

if (!name || !emoji) {
  usage();
  process.exit(1);
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const configPath = resolve(scriptDir, "../references/attribution-config.md");

mkdirSync(dirname(configPath), { recursive: true });
writeFileSync(
  configPath,
  [
    "# Attribution Config",
    "",
    `Agent name: ${markdownInlineCode(name)}`,
    `Emoji: ${markdownInlineCode(emoji)}`,
    "",
    "Generated by `scripts/configure-attribution.ts`.",
    "",
  ].join("\n"),
  "utf8",
);

console.log(`Wrote ${configPath}`);
